version: '3.9'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: localHost
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: mesitas
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DB_HOST=host.docker.internal
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=1234
      - DB_NAME=mesitas
      - JWT_SECRET=mesitas2025
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - db
    restart: always

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
    restart: always

volumes:
  pgdata:
